// This is generated by `build.rs` and contains:
//
//     pub static WORD_LIST: &[(&'static str, i32)] = ...
//
include!(concat!(env!("OUT_DIR"), "/word_list.rs"));

#[derive(Debug, Clone, Copy)]
pub struct Word {
    pub word: &'static str,
    pub count: i32,
}

lazy_static! {
    pub static ref WORDS: Vec<Word> = {
        let mut m = Vec::new();
        for it in WORD_LIST.iter().cloned() {
            let (word, count) = it;
            m.push(Word { word, count });
        }
        m
    };
}
